### ISSUE TITLE
SMART authorization requirement

### ISSUE THREAD

**Issue by jkiddo** [HL7/fhir-ipa#3]
Is it a hard requirement that SMART SHALL/MUST be followed for IPA (https://github.com/HL7/fhir-ipa/blob/main/input/pagecontent/access.md)?

**Comment by grahamegrieve** [comment]
I certainly think it is - it's the key idea of IPA, and I can't imagine how it would have value if it didn't.

**Comment by JohnMoehrke** [comment]
Seems we should be modular regarding security (and privacy). There are other authorization frameworks (e.g. IHE-IUA, which @jkiddo has been a contributor to) https://profiles.ihe.net/ITI/IUA/index.html

**Comment by isaacvetter** [comment]
And @jkiddo, @JohnMoehrke, we've also got a start on how SMART is required here: https://github.com/HL7/fhir-ipa/blob/master/input/pagecontent/security.md

**Comment by isaacvetter** [comment]
Talked through this issue during the HL7 WG PC subcommittee call:
- Confusion around the scope of the IG being limited to patient access. 
- Concern over requiring SMART versus making it recommended and thereby better supporting alternate security mechanisms. 

I'm going to go ahead and close this (e.g. Question answered), let's keep discussing the pros/cons of mandating SMART as the security layer for patient acces.

**Comment by JohnMoehrke** [comment]
Long discussion on the call today that clarified to me that IPA is scoped to Patient themselves accessing their records. This would include apps they authorize specifically using the OAuth authorization methods. It is not intended to be used by other users. (Not clear if this is intended to be used for patient identified delegates).
If this scope is kept as the strict scope, then a binding to SMART with further constraints as currently indicated are appropriate. I do not know of other existing security frameworks (IUA is explicitly not for end-user apps).

There are concerns that this scope is potentially too limited. However the limitation is for the benefit of enabling interop for this specific scope.
